// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/activities/[id]" | "/blog" | "/blog/[slug]" | "/book/[id]" | "/book/bundle" | "/bookings" | "/bookings/[id]/edit" | "/cart" | "/contacts" | "/gallery" | "/packages" | "/packages/[id]" | "/planner" | "/privacy-policy" | "/profile" | "/refund-policy" | "/reviews" | "/terms-of-service" | "/travel-journal"
type AppRouteHandlerRoutes = "/api/activities" | "/api/activities/[id]" | "/api/activities/[id]/availability" | "/api/ai/planner" | "/api/auth/[...nextauth]" | "/api/auth/signup" | "/api/blog" | "/api/bookings" | "/api/bookings/[id]" | "/api/config" | "/api/contacts" | "/api/coupons/validate" | "/api/gallery" | "/api/gemini" | "/api/packages" | "/api/packages/[id]" | "/api/reviews" | "/api/travel-journal" | "/api/user/update"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/activities/[id]": { "id": string; }
  "/api/activities": {}
  "/api/activities/[id]": { "id": string; }
  "/api/activities/[id]/availability": { "id": string; }
  "/api/ai/planner": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/signup": {}
  "/api/blog": {}
  "/api/bookings": {}
  "/api/bookings/[id]": { "id": string; }
  "/api/config": {}
  "/api/contacts": {}
  "/api/coupons/validate": {}
  "/api/gallery": {}
  "/api/gemini": {}
  "/api/packages": {}
  "/api/packages/[id]": { "id": string; }
  "/api/reviews": {}
  "/api/travel-journal": {}
  "/api/user/update": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/book/[id]": { "id": string; }
  "/book/bundle": {}
  "/bookings": {}
  "/bookings/[id]/edit": { "id": string; }
  "/cart": {}
  "/contacts": {}
  "/gallery": {}
  "/packages": {}
  "/packages/[id]": { "id": string; }
  "/planner": {}
  "/privacy-policy": {}
  "/profile": {}
  "/refund-policy": {}
  "/reviews": {}
  "/terms-of-service": {}
  "/travel-journal": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
